# Generated by Django 4.0 on 2022-01-05 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_posts_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='author',
        ),
    ]
