# Generated by Django 4.0 on 2022-01-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_posts_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(default=None, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
