# Generated by Django 4.0 on 2022-01-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_posts_image_alter_posts_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
