# Generated by Django 4.0 on 2022-01-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_posts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='cat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
